Repository openshift/kube-state-metrics, pull requests merged in 2020-08, with the labels that each got.

#28 CARRY: OWNERS: add component
  OWNERS
Labels: approved, lgtm

#32 Bug 1867510: fix CVP issues due to incorrect labels set
  Dockerfile.ocp
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#31 Bug 1862404: Bump to v1.9.7
  CHANGELOG.md
  README.md
  VERSION
  examples/autosharding/cluster-role-binding.yaml
  examples/autosharding/cluster-role.yaml
  examples/autosharding/role-binding.yaml
  examples/autosharding/role.yaml
  examples/autosharding/service-account.yaml
  examples/autosharding/service.yaml
  examples/autosharding/statefulset.yaml
  examples/standard/cluster-role-binding.yaml
  examples/standard/cluster-role.yaml
  examples/standard/deployment.yaml
  examples/standard/service-account.yaml
  examples/standard/service.yaml
  internal/store/builder.go
  internal/store/mutatingwebhookconfiguration.go
  internal/store/mutatingwebhookconfiguration_test.go
  internal/store/validatingwebhookconfiguration.go
  internal/store/validatingwebhookconfiguration_test.go
  internal/store/volumeattachment.go
  internal/store/volumeattachment_test.go
  tests/manifests/mutatingwebhookconfiguration.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
